spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/payment
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /payment
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show-sql: true
    open-in-view: false

logging.level:
  org.hibernate.SQL: DEBUG
  org.hibernate.type: TRACE
  org.springframework.orm.jpa: DEBUG
  org.springframework.transaction: DEBUG
  org.springframework.jdbc: DEBUG
